2_App_admin.sql
Adding few creation of procedures
-- Procedure for adding a new Role
-- Procedure for adding a new Product Category
-- Procedure for adding a new Warehouse
=> Adding few creation of procedures

2_App_admin.sql
Adding procedures for order,user_product,payment
=> Adding procedures for order,user_product,payment

2_App_admin.sql, 3_Grant_App_admin.sql
Adding Grants file based on roles
=> Adding Grants file based on roles

3_Grant_App_admin.sql, 5_Inventory_Manager.sql
Adding grant for customer and inventory manager file
=> Adding grant for customer and inventory manager file

3_Grant_App_admin.sql, 6_customer1.sql, 7_customer2.sql
Adding customer 1 and customer 2 files and granting their accesses
=> Adding customer 1 and customer 2 files and granting their accesses

4_Product_Manager.sql, 6_customer1.sql, 7_customer2.sql
Rectified changes in file 4,6,7
=> Rectified changes in file 4,6,7

README.md
Added instructions for script execution in Readme
=> Added instructions for script execution in Readme

4_Product_Manager.sql, 5_Inventory_Manager.sql, 6_customer1.sql, 7_customer2.sql
Added updated insertions for file 4,5,6,7 for testing
=> Added updated insertions for files 4,5,6,7 for testing

2_App_admin.sql
Corrected the add_procedure parameters
=> Corrected the add_procedure parameters

2_App_admin.sql
Created procedures for users and warehouse insertion
=> Created procedures for users and warehouse insertion

2_App_admin.sql
Committing Create view for customers
=> Committing Create view for customers

2_App_admin.sql
=> Adding trigger for order

2_App_admin.sql
Adding procedures for order,role,user_product
=> Adding procedures for order,role,user_product

2_App_admin.sql
Adding trigger on Payment table
=> Adding trigger on Payment table

7_customer2.sql
=> Adding data for customer2

7_customer2.sql
=> Adding data for customer 2

6_customer1.sql
Adding data for Customer 1 for testing
=> Adding data for Customer 1 for testing

3_Grant_App_admin.sql
Granting access to customer1 and customer2 on views
=> Granting access to customer1 and customer2 on views

7_customer2.sql
Rectified error in customer_2 data
=> Rectified error in customer_2 data

8_App_admin_reports.sql
=> Added report 3

8_App_admin_reports.sql
Adding reports for Customer Purchase History and overall revenue
=> Adding reports for Customer Purchase History and overall revenue
